version: '3.9'

networks:
  cassandra-network:
    driver: bridge
    name: 'cassandra-network'

volumes:
  cassandra-database1:
  cassandra-database2:
  cassandra-database3:

services:
  cassandra1:
    image: cassandra:4.1.1
    container_name: cassandra1
    restart: always
    networks:
      - 'cassandra-network'
    deploy:
      replicas: 1
    volumes:
      - type: volume
        source: cassandra-database1
        target: /var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: 'cassandra_cluster'
      CASSANDRA_DC: 'west-side'
      CASSANDRA_ENDPOINT_SNITCH: 'org.apache.cassandra.locator.GossipingPropertyFileSnitch'
  cassandra2:
    image: cassandra:4.1.1
    container_name: cassandra2
    restart: always
    networks:
      - 'cassandra-network'
    deploy:
      replicas: 1
    volumes:
      - type: volume
        source: cassandra-database2
        target: /var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: 'cassandra_cluster'
      CASSANDRA_DC: 'west-side'
      CASSANDRA_SEEDS: cassandra1
      CASSANDRA_ENDPOINT_SNITCH: 'org.apache.cassandra.locator.GossipingPropertyFileSnitch'
  cassandra3:
    image: cassandra:4.1.1
    container_name: cassandra3
    restart: always
    networks:
      - 'cassandra-network'
    deploy:
      replicas: 1
    volumes:
      - type: volume
        source: cassandra-database3
        target: /var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: 'cassandra_cluster'
      CASSANDRA_DC: 'east-side'
      CASSANDRA_SEEDS: cassandra1
      CASSANDRA_ENDPOINT_SNITCH: 'org.apache.cassandra.locator.GossipingPropertyFileSnitch'

# CREATE KEYSPACE abc WITH replication = {'class': 'NetworkTopologyStrategy', 'west-side': '1', 'east-side': '1'}  AND durable_writes = true;